# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Engram < Formula
  desc "Auto-memory system for AI coding agents"
  homepage "https://github.com/shiblon/engram"
  version "0.6.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shiblon/engram/releases/download/v0.6.2/engram_0.6.2_darwin_amd64.tar.gz"
      sha256 "62a2ecb5319e8c4ea3aee76c5f76896cd82635ccae90fa86f5633f5756d87abe"

      define_method(:install) do
        bin.install "engram"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shiblon/engram/releases/download/v0.6.2/engram_0.6.2_darwin_arm64.tar.gz"
      sha256 "1134b9a548d89c0e918fcbf2132f96cbfa25d04e9320c85c93f1c187efcd87c6"

      define_method(:install) do
        bin.install "engram"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shiblon/engram/releases/download/v0.6.2/engram_0.6.2_linux_amd64.tar.gz"
      sha256 "af6e90388373de041245daa03d20de561a973ae9fb9fcb941cdf00514c92e176"
      define_method(:install) do
        bin.install "engram"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shiblon/engram/releases/download/v0.6.2/engram_0.6.2_linux_arm64.tar.gz"
      sha256 "a487b0e3b6fe48fb105d87276ceab88c7b72da63fa0e8bd20b25aca63dbe46b8"
      define_method(:install) do
        bin.install "engram"
      end
    end
  end

  test do
    system bin/"engram", "--version"
  end
end
