# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Engram < Formula
  desc "Auto-memory system for AI coding agents"
  homepage "https://github.com/shiblon/engram"
  version "0.5.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shiblon/engram/releases/download/v0.5.1/engram_0.5.1_darwin_amd64.tar.gz"
      sha256 "537ad84fe01f70fea3e207f6b7d31a414f3efbeff91652354c60e9f2f8c3dc8c"

      define_method(:install) do
        bin.install "engram"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shiblon/engram/releases/download/v0.5.1/engram_0.5.1_darwin_arm64.tar.gz"
      sha256 "69f87a9b2fbfe0ba03603a8967237d0deed3e388e8c3eafb79678eee06625756"

      define_method(:install) do
        bin.install "engram"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shiblon/engram/releases/download/v0.5.1/engram_0.5.1_linux_amd64.tar.gz"
      sha256 "15670576c9a5f08c721827f47c165358738a949e7b9a5918fde49b035467fc4c"
      define_method(:install) do
        bin.install "engram"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shiblon/engram/releases/download/v0.5.1/engram_0.5.1_linux_arm64.tar.gz"
      sha256 "7e665b41769d4cb2b66a92a00a34c6905cac4e885a6c3e7e5e4623e31fdf5bb8"
      define_method(:install) do
        bin.install "engram"
      end
    end
  end

  test do
    system bin/"engram", "--version"
  end
end
