# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Engram < Formula
  desc "Auto-memory system for AI coding agents"
  homepage "https://github.com/shiblon/engram"
  version "0.8.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shiblon/engram/releases/download/v0.8.1/engram_0.8.1_darwin_amd64.tar.gz"
      sha256 "8fb4d19923519d3dd5c2fa9f600d974eafcf6ebbd65eb5d86e64bc1c97ee6a78"

      define_method(:install) do
        bin.install "engram"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shiblon/engram/releases/download/v0.8.1/engram_0.8.1_darwin_arm64.tar.gz"
      sha256 "d7eaa00e274cbf933ed8f94d38e90d57d2f77e57ad82a62645d89bf36edb257a"

      define_method(:install) do
        bin.install "engram"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shiblon/engram/releases/download/v0.8.1/engram_0.8.1_linux_amd64.tar.gz"
      sha256 "684dc5f1fc397357753b8a2ba6ededd05a720fa1606e98df53ff2c52e90365db"
      define_method(:install) do
        bin.install "engram"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shiblon/engram/releases/download/v0.8.1/engram_0.8.1_linux_arm64.tar.gz"
      sha256 "898d4520f24e29a1399ad69edc09edc2ba03ac0eb97a33cc4457e4d1d11fc9ca"
      define_method(:install) do
        bin.install "engram"
      end
    end
  end

  test do
    system bin/"engram", "--version"
  end
end
