# This file was generated by GoReleaser. DO NOT EDIT.
cask "engram" do
  version "0.15.0"

  on_macos do
    on_arm do
      sha256 "3e5201ff4b30b105052e82273fcfbc9aac8093c8bf731edbf1f44a3aca239214"
      url "https://github.com/shiblon/engram/releases/download/v#{version}/engram_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a08dc1b66d5b796ddd77854e77aa6fa21e74c13feb62e402e00b9c14992ca9f6"
      url "https://github.com/shiblon/engram/releases/download/v#{version}/engram_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "dc43b89be57426668a4e91cde22132ab33b0b282179351d11f3f50e0e7046542"
      url "https://github.com/shiblon/engram/releases/download/v#{version}/engram_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5b8f125586163b37a23fcbe0ea9da91140f06b32980d1ac81fe7ced922fad127"
      url "https://github.com/shiblon/engram/releases/download/v#{version}/engram_#{version}_linux_amd64.tar.gz"
    end
  end

  name "engram"
  desc "Auto-memory system for AI coding agents"
  homepage "https://github.com/shiblon/engram"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "engram"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/engram"]
    end
  end

  # No zap stanza required
end
