# This file was generated by GoReleaser. DO NOT EDIT.
cask "engram" do
  version "0.16.1"

  on_macos do
    on_arm do
      sha256 "520a633ca90036697d045cc88171341b24b2198e9e8b03aae124ffec3e5538ed"
      url "https://github.com/shiblon/engram/releases/download/v#{version}/engram_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8150b78da3cb0dacf1a675a172fdbb58381159d43f7faa36056008e5b35638bc"
      url "https://github.com/shiblon/engram/releases/download/v#{version}/engram_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b4140e811bf942d35555c2a11644a10bda0ce4bb090ff13bfb4d49c7aa7ede1f"
      url "https://github.com/shiblon/engram/releases/download/v#{version}/engram_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e9d5de3c61b99cb21a31707bfd764efd24786449cd07b67426a725053a5c09d9"
      url "https://github.com/shiblon/engram/releases/download/v#{version}/engram_#{version}_linux_amd64.tar.gz"
    end
  end

  name "engram"
  desc "Auto-memory system for AI coding agents"
  homepage "https://github.com/shiblon/engram"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "engram"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/engram"]
    end
  end

  # No zap stanza required
end
