# This file was generated by GoReleaser. DO NOT EDIT.
cask "engram" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args:           ["-dr", "com.apple.quarantine", "{{staged_path}}/engram"],
          writable_paths: ["{{staged_path}}/engram"]
    end
  end

  version "0.16.5"

  on_macos do
    on_arm do
      sha256 "d4800d5bc2997a1f76dc9799b76a2adbf148cbf13f15c0a1391238f4d987db06"
      url "https://github.com/shiblon/engram/releases/download/v#{version}/engram_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "53ca6fffbbaa45799f031358b3a3e8a2368af1ca6cbf42198e4dbd7d73e6049e"
      url "https://github.com/shiblon/engram/releases/download/v#{version}/engram_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f419e1c1e23a2bb25824048d5b4f70236b41784e0e5a39254ff9af83129d13b3"
      url "https://github.com/shiblon/engram/releases/download/v#{version}/engram_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7daa274da66997c6121dbc2c0f842e8db400368e2a1029b768a79aee307ac882"
      url "https://github.com/shiblon/engram/releases/download/v#{version}/engram_#{version}_linux_amd64.tar.gz"
    end
  end

  name "engram"
  desc "Auto-memory system for AI coding agents"
  homepage "https://github.com/shiblon/engram"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "engram"

  # No zap stanza required
end
